<?php
/**
 * Created by PhpStorm.
 * User: lhz
 * Date: 2017/1/12
 * Time: 下午9:47
 */
namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    //指定表ming
    protected  $table='student';

    //指定id
    protected  $primaryKey='id';

    protected  $timestamps=false;

    protected $fillable=['name','age'];

    protected $guarded=[];

    protected  function getDateFormat()
    {
        return time(); // TODO: Change the autogenerated stub
    }

    protected function asDateTime($value)
    {
        return parent::asDateTime($value); // TODO: Change the autogenerated stub
    }
}